version: '3.8'

services:
  kimpscan1:
    image: amazoncorretto:21-alpine3.20
    volumes:
      - ./build/libs/snippet-0.0.1-SNAPSHOT.jar:/spring.jar
    command: ["java", "-Dspring.kafka.bootstrap-servers=kafka:9092", "-jar", "/spring.jar"]
    networks:
      - docker_net

  kimpscan2:
    image: amazoncorretto:21-alpine3.20
    volumes:
      - ./build/libs/snippet-0.0.1-SNAPSHOT.jar:/spring.jar
    command: ["java", "-Dspring.kafka.bootstrap-servers=kafka:9092", "-jar", "/spring.jar"]
    networks:
      - docker_net

  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # 메모리 제한을 200MB로 설정
      - KAFKA_CFG_HEAP_OPTS="-Xmx200M -Xms200M"  # 최대 및 최소 힙 메모리 크기 200MB로 설정
      - KAFKA_CFG_LOG_SEGMENT_BYTES=10485760  # 로그 세그먼트 크기: 10MB
      - KAFKA_CFG_NUM_PARTITIONS=1  # 파티션 수: 1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false # 자동 토픽 생성 막기
      - KAFKA_CFG_LOG_RETENTION_HOURS=1 # 세그먼트 파일의 삭제 주기: 1시간
    ports:
      - "9092:9092"  # Kafka 외부 접속 포트
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge

volumes:
  kafka_data:
    driver: local
